<a href="https://colab.research.google.com/github/sagar-kc7/pytorch_fundamentals/blob/main/01_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Fundammentals**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.10.0+cu128


## Introduction to Tensor

### *Creating Tensors*

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
matrix = torch.tensor([[1, 3],
                       [3, 4]])
matrix


tensor([[1, 3],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
#Tensor

Tensor = torch.tensor([[[1,2,3],
                        [2,3,4],
                        [3,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [ ]:
print(Tensor.ndim)
Tensor.shape

3


torch.Size([1, 3, 3])

In [ ]:
Tensor[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

### *Random Tensor*

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2096, 0.8780, 0.3034, 0.0607],
        [0.3414, 0.8374, 0.8728, 0.0389],
        [0.9722, 0.6030, 0.9208, 0.4543]])

In [ ]:
# Tensors of all Zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Tensors of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of Tensors

In [ ]:
one_to_ten = torch.arange(1, 11)

In [ ]:
# Tensor like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

In [ ]:
float_32_tensor = torch.tensor([3,4],
                               dtype=None)
float_32_tensor

tensor([3, 4])

In [ ]:
float_32_tensor.dtype

#it's int lets change to float32

torch.int64

In [ ]:
int_to_float32 = float_32_tensor.type(torch.float32)
int_to_float32.dtype

torch.float32

### Aggregation

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

### Stacking, Squeeze and Unsqueeze

In [ ]:
x = torch.zeros(2,1,2,1,2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [ ]:
y = torch.squeeze(x)
y, y.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [ ]:
y_unsqueezed = torch.unsqueeze(input=y, dim=0)
y_unsqueezed, y_unsqueezed.shape

(tensor([[[1, 2, 3, 4]]]), torch.Size([1, 1, 4]))

### Indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0][2][1]

tensor(8)

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, :]

tensor([[4, 5, 6]])

### PyTorch and NumPy

In [ ]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))